# Generated by Django 4.0.2 on 2022-02-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_view_all_books', 'View all borrowed books'), ('can_renew', 'renew a book'))},
        ),
    ]
